"""creating table

Revision ID: 983e878ff980
Revises: 
Create Date: 2025-01-09 12:04:21.301373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983e878ff980'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('ph_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('ph_no')
    )
    op.create_table('Asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('sl_no', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('warranty_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allocated_to', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allocated_to'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['Employee.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ticket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(length=100), nullable=False),
    sa.Column('ticket_status', sa.String(length=100), nullable=False),
    sa.Column('assigned_date', sa.TIMESTAMP(), nullable=True),
    sa.Column('returned_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('returned_condition', sa.String(length=100), nullable=False),
    sa.Column('raised_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ticket')
    op.drop_table('Notification')
    op.drop_table('Asset')
    op.drop_table('Employee')
    # ### end Alembic commands ###
