"""changed fields from ticket to asset

Revision ID: 5921e6429062
Revises: 40919cf4bf8c
Create Date: 2025-01-15 11:08:43.955744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5921e6429062'
down_revision: Union[str, None] = '40919cf4bf8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    op.add_column('asset', sa.Column('return_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'return_date')
    op.drop_column('asset', 'assigned_date')
    
    # ### end Alembic commands ###
