"""Initial migration

Revision ID: 7351a4fc4025
Revises: 
Create Date: 2025-01-10 12:00:40.314500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7351a4fc4025'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Asset',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('asset_model', sa.VARCHAR(length=100), nullable=False),
    sa.Column('asset_sl_no', sa.VARCHAR(length=100), nullable=False),
    sa.Column('asset_purchasedate', sa.TIMESTAMP(), nullable=True),
    sa.Column('asset_warranty_end', sa.TIMESTAMP(), nullable=True),
    sa.Column('asset_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('Employee',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('department', sa.VARCHAR(length=50), nullable=False),
    sa.Column('designation', sa.VARCHAR(length=50), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('date_joined', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['Employee.employee_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['Employee.employee_id'], ),
    sa.PrimaryKeyConstraint('notification_id'),
    sa.UniqueConstraint('message')
    )
    op.create_table('Ticket',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('ticket_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ticket_status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('returned_condition', sa.VARCHAR(length=255), nullable=False),
    sa.Column('raised_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('resolved_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['Asset.asset_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.employee_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ticket')
    op.drop_table('Notification')
    op.drop_table('Employee')
    op.drop_table('Asset')
    # ### end Alembic commands ###
