"""Initial migration

Revision ID: a6822af551da
Revises: d7028fac7dca
Create Date: 2025-01-10 12:06:50.968491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6822af551da'
down_revision: Union[str, None] = 'd7028fac7dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('message', table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sent_at', mysql.DATETIME(), nullable=True),
    sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['employee.employee_id'], name='notification_ibfk_1'),
    sa.ForeignKeyConstraint(['sender_id'], ['employee.employee_id'], name='notification_ibfk_2'),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('message', 'notification', ['message'], unique=True)
    # ### end Alembic commands ###
