"""Create  Table

Revision ID: b85a7efb783b
Revises: 
Create Date: 2025-01-14 11:56:22.826706

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85a7efb783b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('designation', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('asset',
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('asset_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('asset_sl_no', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('asset_purchasedate', sa.DateTime(), nullable=True),
    sa.Column('asset_warranty_end', sa.DateTime(), nullable=True),
    sa.Column('asset_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('allocated_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allocated_to'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['employee.employee_id'], ),
    sa.PrimaryKeyConstraint('notification_id'),
    sa.UniqueConstraint('message')
    )
    op.create_table('Ticket',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('ticket_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ticket_status', sa.Integer(), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('returned_condition', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('raised_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['ticket_status'], ['notification.notification_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ticket')
    op.drop_table('notification')
    op.drop_table('asset')
    op.drop_table('employee')
    # ### end Alembic commands ###
