"""Initial migration

Revision ID: d7028fac7dca
Revises: 7351a4fc4025
Create Date: 2025-01-10 12:06:00.039899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7028fac7dca'
down_revision: Union[str, None] = '7351a4fc4025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.alter_column('asset', 'asset_purchasedate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('asset', 'asset_warranty_end',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('employee', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('employee', 'date_joined',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('employee', 'phone')
    op.alter_column('notification', 'sent_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'sent_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('employee', sa.Column('phone', mysql.VARCHAR(length=15), nullable=False))
    op.alter_column('employee', 'date_joined',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('employee', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('asset', 'asset_warranty_end',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('asset', 'asset_purchasedate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('ticket',
    sa.Column('ticket_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticket_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ticket_status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('assigned_date', sa.DATE(), nullable=True),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.Column('returned_condition', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('raised_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('resolved_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.asset_id'], name='ticket_ibfk_1'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], name='ticket_ibfk_2'),
    sa.PrimaryKeyConstraint('ticket_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
