"""changed field from ticket to asset

Revision ID: 7077fcc18e10
Revises: b4e6f0101678
Create Date: 2025-01-15 11:28:16.432161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7077fcc18e10'
down_revision: Union[str, None] = 'b4e6f0101678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'return_date')
    op.drop_column('ticket', 'assigned_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('return_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
