"""changed field from ticket to asset

Revision ID: b4e6f0101678
Revises: 0099c07cd6e3
Create Date: 2025-01-15 11:20:17.011852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b4e6f0101678'
down_revision: Union[str, None] = '0099c07cd6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'return_date')
    op.drop_column('ticket', 'assigned_date')
    op.add_column('asset', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    op.add_column('asset', sa.Column('return_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'return_date')
    op.drop_column('asset', 'assigned_date')
    op.add_column('ticket', sa.Column('assigned_date', sa.DateTime(), nullable=True))
    op.add_column('ticket', sa.Column('return_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
